---
JumioIntegrationService: 
  Db:
    LogsConnString: 
      settings-key: KycReports-LogsConnString
      types: [AzureTableStorage] 
    ReportsConnString:  
      settings-key: KycReports-ReportsConnString
      types: [AzureTableStorage] 
  KycServiceSettings:
    ServiceUri:
      settings-key: KycServiceUrl
    ApiKey:
      settings-key: KycApiKey
SlackNotifications:
  AzureQueue:
    ConnectionString:
      settings-key: SlackNotificationsConnString
      types: [AzureTableStorage]
    QueueName:
      settings-key: SlackNotificationsQueueName
  ThrottlingLimitSeconds:
      settings-key: SlackNotificationsThrottlingLimit
ClientAccountServiceClient:
  ServiceUrl:
   settings-key: ClientAccountServiceUrl
PersonalDataServiceClient:
  ServiceUri:
    settings-key: PersonalDataServiceUrl
  ApiKey:
    settings-key: PersonalDataApiKey
